### ISSUE TITLE
Fix vulnerabilities

### ISSUE THREAD

**Issue by Seqi** [Seqi/raifu#103]

**Comment by MuhaddiMu** [comment]
What are the vulnerabilities?
Please add a list and be more specific. I'd be happy to contribute!

**Comment by Seqi** [comment]
Hi MuhaddiMu,

The vulnerabilities seem to lie in lodash https://github.com/Seqi/raifu/network/alerts which is being used as a dependency for quite a few packages we're using. Not too sure the extent of the updates needed (hopefully no breaking changes!) but i've not had a chance to run `npm audit` yet :(

**Comment by MuhaddiMu** [comment]
Hi @Seqi I'm unable to view the security alert page due to roles. It'd be better if you paste the raw here.

If you are using a vulnerable dependency as a package. It'd be better to update but if for some reasons you are unable to do so. I'll suggest taking a look changelogs of loadash and there you got to know what are the impacts of that vulnerability and how to mitigate it. If it's affecting your code then just implement a possible fix otherwise no problems updating it.
